# CMake generated Testfile for 
# Source directory: /home/ivan/Desktop/projects/ccvpn/ccvpn/gateway/ccnx/forwarder/athena/test
# Build directory: /home/ivan/Desktop/projects/ccvpn/ccvpn/b/gateway/ccnx/forwarder/athena/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_athena "test_athena")
set_tests_properties(test_athena PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_pair "test_athena_pair")
set_tests_properties(test_athena_pair PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_FIB "test_athena_FIB")
set_tests_properties(test_athena_FIB PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_PIT "test_athena_PIT")
set_tests_properties(test_athena_PIT PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkAdapter "test_athena_TransportLinkAdapter")
set_tests_properties(test_athena_TransportLinkAdapter PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLink "test_athena_TransportLink")
set_tests_properties(test_athena_TransportLink PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkModule "test_athena_TransportLinkModule")
set_tests_properties(test_athena_TransportLinkModule PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkModuleTCP "test_athena_TransportLinkModuleTCP")
set_tests_properties(test_athena_TransportLinkModuleTCP PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkModuleUDP "test_athena_TransportLinkModuleUDP")
set_tests_properties(test_athena_TransportLinkModuleUDP PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkModuleETH "test_athena_TransportLinkModuleETH")
set_tests_properties(test_athena_TransportLinkModuleETH PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_TransportLinkModuleTEMPLATE "test_athena_TransportLinkModuleTEMPLATE")
set_tests_properties(test_athena_TransportLinkModuleTEMPLATE PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_ContentStore "test_athena_ContentStore")
set_tests_properties(test_athena_ContentStore PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_LRUContentStore "test_athena_LRUContentStore")
set_tests_properties(test_athena_LRUContentStore PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athena_InterestControl "test_athena_InterestControl")
set_tests_properties(test_athena_InterestControl PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
add_test(test_athenactl "test_athenactl")
set_tests_properties(test_athenactl PROPERTIES  ENVIRONMENT "LD_LIBRARY_PATH=/home/ivan/Desktop/projects/ccvpn/ccvpn/b/ccnx/forwarder/athena")
